### ISSUE TITLE
Too many arguments, expected arguments "command" "config_name" "key"

### ISSUE THREAD

**Issue by drishu** [openeuropa/oe_bootstrap_theme#63] opened 2021-08-28 16:24 UTC
see https://drone.fpfis.eu/openeuropa/oe_bootstrap_theme/317/19
I was able to reproduce on local, after runner has run though, so:
composer install
run drupal:site-install
./vendor/bin/drush cset system.theme default oe_bootstrap_theme -y

I've found the solution to be ./vendor/bin/drush cset system.theme default --value=oe_bootstrap_theme -y

Still strange though, I've looked into green builds, same command gave no errors under the same drush version 10.6.0

**Comment by shean42** [comment] 2021-08-29 03:50
The above work-around does not seem to work, at least on my end! While it gets around the drush error message the value actually is not set in the configuration. No matter which value is passed to cset, the configuration always stores '2' :-/

You might want to follow this [drush issue](https://github.com/drush-ops/drush/issues/4813).

**Comment by brummbar** [comment] 2021-09-09 08:54
Issue was on drush side. Is it solved?

**Comment by AaronGilMartinez** [comment] 2024-09-30 06:31
Hello @shean42 drush issue was solved time ago, if the issue is till present can you provide steps to reproduce, please?
If not the case you can close the issue.

**Comment by shean42** [comment] 2024-09-30 12:30
It's safe to close this one, thanks! Although I don't seem to have the powers to do so ;-)

**Comment by AaronGilMartinez** [comment] 2024-09-30 12:32
OK, thanks @shean42

**Closed as completed by AaronGilMartinez** 2024-09-30 12:32 UTC
Labels: to be confirmed
